# Dependencies
markdown:         redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter:      rouge

# Permalinks
permalink:        :year/:month/:day/:title
#relative_permalinks: true

# Setup
title:            El Javi
tagline:          'Yet another dev blog'
url:              http://javierholguera.github.io
baseurl:          /

author:
  name:           'Javier Holguera'
  url:            https://twitter.com/javierholguera

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems:
  - jekyll-paginate
  - jekyll-gist
